# Generated by Django 2.0.6 on 2018-06-22 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=30)),
                ('phone2', models.CharField(max_length=30)),
                ('jobname', models.CharField(max_length=255)),
                ('placename', models.CharField(max_length=255)),
                ('note', models.TextField()),
            ],
        ),
    ]
