# Generated by Django 2.0.6 on 2018-06-23 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
                ('received_at', models.DateField(null=True)),
                ('paidSum', models.PositiveIntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Customer')),
            ],
        ),
    ]
