# Generated by Django 2.0.6 on 2018-06-24 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_customerbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='books',
            field=models.ManyToManyField(through='books.CustomerBook', to='books.Book'),
        ),
    ]
